apiVersion: apps/v1

kind: Deployment
metadata:
  name: mvcapp
  namespace: prod
spec:
  selector:
    matchLabels:
      app: mvcapp
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mvcapp
    spec:
      containers:
      - name: mvcapp
        image: enes.local.registry:5000/mvcapp:${DOCKER_BUILD_NUMBER}v
        env:
          - name: PORT
            value: "80"
          - name: ASPNETCORE_ENVIRONMENT
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "0.5"
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            port: 80
          successThreshold: 1
          failureThreshold: 5
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 80
          successThreshold: 1
          failureThreshold: 5
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 5
