apiVersion: v1
kind: Service
metadata:
  name: mvcapp
  namespace: prod
spec:
  selector:
    app: mvcapp
  type: NodePort
  ports:
  - name: http
    nodePort: 31977
    port: 80
    targetPort: 80
    protocol: TCP